# Generated by Django 5.1.1 on 2024-09-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted by AI'), ('rejected', 'Rejected by AI'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
