# Generated by Django 5.1.1 on 2024-09-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_report_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='file_url',
        ),
        migrations.AddField(
            model_name='report',
            name='file_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
