# Generated by Django 5.1.1 on 2024-10-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
