# Generated by Django 5.1.1 on 2024-10-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_report_options_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
