# Generated by Django 5.1.1 on 2024-10-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_report_options_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='manual_status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
